/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iapractica.views;

import iapractica.views.myPanels.MyPanelImage;
import javax.swing.JScrollPane;

/**
 *
 * @author Justo Vargas
 */
public class VerImagen extends javax.swing.JFrame {

    /**
     * Creates new form VerImagen
     */
    public VerImagen(String path) {
        initComponents();
        MyPanelImage myP = new MyPanelImage(path);
        //jScrollPane1.setViewportView();
        this.jPanel1.add(myP);
        this.setTitle(path);
        this.setSize(myP.getImageSize());
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout());
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
